/* soapWSHttpBinding_USCOREINWNMasterServerAPIProxy.h
   Generated by gSOAP 2.8.11 from NWNlist.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/
#pragma once
#ifndef soapWSHttpBinding_USCOREINWNMasterServerAPIProxy_H
#define soapWSHttpBinding_USCOREINWNMasterServerAPIProxy_H
#include "soapH.h"

class SOAP_CMAC WSHttpBinding_USCOREINWNMasterServerAPIProxy : public soap
{ public:
	/// Endpoint URL of service 'WSHttpBinding_USCOREINWNMasterServerAPIProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WSHttpBinding_USCOREINWNMasterServerAPIProxy();
	/// Construct from another engine state
	WSHttpBinding_USCOREINWNMasterServerAPIProxy(const struct soap&);
	/// Constructor with endpoint URL
	WSHttpBinding_USCOREINWNMasterServerAPIProxy(const char *url);
	/// Constructor with engine input+output mode control
	WSHttpBinding_USCOREINWNMasterServerAPIProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	WSHttpBinding_USCOREINWNMasterServerAPIProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	WSHttpBinding_USCOREINWNMasterServerAPIProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WSHttpBinding_USCOREINWNMasterServerAPIProxy();
	/// Initializer used by constructors
	virtual	void WSHttpBinding_USCOREINWNMasterServerAPIProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'LookupServerByName' (returns error code or SOAP_OK)
	virtual	int LookupServerByName(_ns1__LookupServerByName *ns1__LookupServerByName, _ns1__LookupServerByNameResponse *ns1__LookupServerByNameResponse) { return this->LookupServerByName(NULL, NULL, ns1__LookupServerByName, ns1__LookupServerByNameResponse); }
	virtual	int LookupServerByName(const char *endpoint, const char *soap_action, _ns1__LookupServerByName *ns1__LookupServerByName, _ns1__LookupServerByNameResponse *ns1__LookupServerByNameResponse);

	/// Web service operation 'LookupServerByAddress' (returns error code or SOAP_OK)
	virtual	int LookupServerByAddress(_ns1__LookupServerByAddress *ns1__LookupServerByAddress, _ns1__LookupServerByAddressResponse *ns1__LookupServerByAddressResponse) { return this->LookupServerByAddress(NULL, NULL, ns1__LookupServerByAddress, ns1__LookupServerByAddressResponse); }
	virtual	int LookupServerByAddress(const char *endpoint, const char *soap_action, _ns1__LookupServerByAddress *ns1__LookupServerByAddress, _ns1__LookupServerByAddressResponse *ns1__LookupServerByAddressResponse);

	/// Web service operation 'GetOnlineServerList' (returns error code or SOAP_OK)
	virtual	int GetOnlineServerList(_ns1__GetOnlineServerList *ns1__GetOnlineServerList, _ns1__GetOnlineServerListResponse *ns1__GetOnlineServerListResponse) { return this->GetOnlineServerList(NULL, NULL, ns1__GetOnlineServerList, ns1__GetOnlineServerListResponse); }
	virtual	int GetOnlineServerList(const char *endpoint, const char *soap_action, _ns1__GetOnlineServerList *ns1__GetOnlineServerList, _ns1__GetOnlineServerListResponse *ns1__GetOnlineServerListResponse);

	/// Web service operation 'GetOnlineUserCount' (returns error code or SOAP_OK)
	virtual	int GetOnlineUserCount(_ns1__GetOnlineUserCount *ns1__GetOnlineUserCount, _ns1__GetOnlineUserCountResponse *ns1__GetOnlineUserCountResponse) { return this->GetOnlineUserCount(NULL, NULL, ns1__GetOnlineUserCount, ns1__GetOnlineUserCountResponse); }
	virtual	int GetOnlineUserCount(const char *endpoint, const char *soap_action, _ns1__GetOnlineUserCount *ns1__GetOnlineUserCount, _ns1__GetOnlineUserCountResponse *ns1__GetOnlineUserCountResponse);

	/// Web service operation 'GetSupportedProductList' (returns error code or SOAP_OK)
	virtual	int GetSupportedProductList(_ns1__GetSupportedProductList *ns1__GetSupportedProductList, _ns1__GetSupportedProductListResponse *ns1__GetSupportedProductListResponse) { return this->GetSupportedProductList(NULL, NULL, ns1__GetSupportedProductList, ns1__GetSupportedProductListResponse); }
	virtual	int GetSupportedProductList(const char *endpoint, const char *soap_action, _ns1__GetSupportedProductList *ns1__GetSupportedProductList, _ns1__GetSupportedProductListResponse *ns1__GetSupportedProductListResponse);

	/// Web service operation 'LookupServerByModule' (returns error code or SOAP_OK)
	virtual	int LookupServerByModule(_ns1__LookupServerByModule *ns1__LookupServerByModule, _ns1__LookupServerByModuleResponse *ns1__LookupServerByModuleResponse) { return this->LookupServerByModule(NULL, NULL, ns1__LookupServerByModule, ns1__LookupServerByModuleResponse); }
	virtual	int LookupServerByModule(const char *endpoint, const char *soap_action, _ns1__LookupServerByModule *ns1__LookupServerByModule, _ns1__LookupServerByModuleResponse *ns1__LookupServerByModuleResponse);

	/// Web service operation 'RegisterPendingServers' (returns error code or SOAP_OK)
	virtual	int RegisterPendingServers(_ns1__RegisterPendingServers *ns1__RegisterPendingServers, _ns1__RegisterPendingServersResponse *ns1__RegisterPendingServersResponse) { return this->RegisterPendingServers(NULL, NULL, ns1__RegisterPendingServers, ns1__RegisterPendingServersResponse); }
	virtual	int RegisterPendingServers(const char *endpoint, const char *soap_action, _ns1__RegisterPendingServers *ns1__RegisterPendingServers, _ns1__RegisterPendingServersResponse *ns1__RegisterPendingServersResponse);

	/// Web service operation 'LookupServerByGameType' (returns error code or SOAP_OK)
	virtual	int LookupServerByGameType(_ns1__LookupServerByGameType *ns1__LookupServerByGameType, _ns1__LookupServerByGameTypeResponse *ns1__LookupServerByGameTypeResponse) { return this->LookupServerByGameType(NULL, NULL, ns1__LookupServerByGameType, ns1__LookupServerByGameTypeResponse); }
	virtual	int LookupServerByGameType(const char *endpoint, const char *soap_action, _ns1__LookupServerByGameType *ns1__LookupServerByGameType, _ns1__LookupServerByGameTypeResponse *ns1__LookupServerByGameTypeResponse);

	/// Web service operation 'GetClientExtensionUpdate' (returns error code or SOAP_OK)
	virtual	int GetClientExtensionUpdate(_ns1__GetClientExtensionUpdate *ns1__GetClientExtensionUpdate, _ns1__GetClientExtensionUpdateResponse *ns1__GetClientExtensionUpdateResponse) { return this->GetClientExtensionUpdate(NULL, NULL, ns1__GetClientExtensionUpdate, ns1__GetClientExtensionUpdateResponse); }
	virtual	int GetClientExtensionUpdate(const char *endpoint, const char *soap_action, _ns1__GetClientExtensionUpdate *ns1__GetClientExtensionUpdate, _ns1__GetClientExtensionUpdateResponse *ns1__GetClientExtensionUpdateResponse);

	/// Web service operation 'LookupServerByGameTypeClientExtension' (returns error code or SOAP_OK)
	virtual	int LookupServerByGameTypeClientExtension(_ns1__LookupServerByGameTypeClientExtension *ns1__LookupServerByGameTypeClientExtension, _ns1__LookupServerByGameTypeClientExtensionResponse *ns1__LookupServerByGameTypeClientExtensionResponse) { return this->LookupServerByGameTypeClientExtension(NULL, NULL, ns1__LookupServerByGameTypeClientExtension, ns1__LookupServerByGameTypeClientExtensionResponse); }
	virtual	int LookupServerByGameTypeClientExtension(const char *endpoint, const char *soap_action, _ns1__LookupServerByGameTypeClientExtension *ns1__LookupServerByGameTypeClientExtension, _ns1__LookupServerByGameTypeClientExtensionResponse *ns1__LookupServerByGameTypeClientExtensionResponse);

	/// Web service operation 'IncrementStatistic' (returns error code or SOAP_OK)
	virtual	int IncrementStatistic(_ns1__IncrementStatistic *ns1__IncrementStatistic, _ns1__IncrementStatisticResponse *ns1__IncrementStatisticResponse) { return this->IncrementStatistic(NULL, NULL, ns1__IncrementStatistic, ns1__IncrementStatisticResponse); }
	virtual	int IncrementStatistic(const char *endpoint, const char *soap_action, _ns1__IncrementStatistic *ns1__IncrementStatistic, _ns1__IncrementStatisticResponse *ns1__IncrementStatisticResponse);

	/// Web service operation 'LookupServerByName' (returns error code or SOAP_OK)
	virtual	int LookupServerByName_(_ns1__LookupServerByName *ns1__LookupServerByName, _ns1__LookupServerByNameResponse *ns1__LookupServerByNameResponse) { return this->LookupServerByName_(NULL, NULL, ns1__LookupServerByName, ns1__LookupServerByNameResponse); }
	virtual	int LookupServerByName_(const char *endpoint, const char *soap_action, _ns1__LookupServerByName *ns1__LookupServerByName, _ns1__LookupServerByNameResponse *ns1__LookupServerByNameResponse);

	/// Web service operation 'LookupServerByAddress' (returns error code or SOAP_OK)
	virtual	int LookupServerByAddress_(_ns1__LookupServerByAddress *ns1__LookupServerByAddress, _ns1__LookupServerByAddressResponse *ns1__LookupServerByAddressResponse) { return this->LookupServerByAddress_(NULL, NULL, ns1__LookupServerByAddress, ns1__LookupServerByAddressResponse); }
	virtual	int LookupServerByAddress_(const char *endpoint, const char *soap_action, _ns1__LookupServerByAddress *ns1__LookupServerByAddress, _ns1__LookupServerByAddressResponse *ns1__LookupServerByAddressResponse);

	/// Web service operation 'GetOnlineServerList' (returns error code or SOAP_OK)
	virtual	int GetOnlineServerList_(_ns1__GetOnlineServerList *ns1__GetOnlineServerList, _ns1__GetOnlineServerListResponse *ns1__GetOnlineServerListResponse) { return this->GetOnlineServerList_(NULL, NULL, ns1__GetOnlineServerList, ns1__GetOnlineServerListResponse); }
	virtual	int GetOnlineServerList_(const char *endpoint, const char *soap_action, _ns1__GetOnlineServerList *ns1__GetOnlineServerList, _ns1__GetOnlineServerListResponse *ns1__GetOnlineServerListResponse);

	/// Web service operation 'GetOnlineUserCount' (returns error code or SOAP_OK)
	virtual	int GetOnlineUserCount_(_ns1__GetOnlineUserCount *ns1__GetOnlineUserCount, _ns1__GetOnlineUserCountResponse *ns1__GetOnlineUserCountResponse) { return this->GetOnlineUserCount_(NULL, NULL, ns1__GetOnlineUserCount, ns1__GetOnlineUserCountResponse); }
	virtual	int GetOnlineUserCount_(const char *endpoint, const char *soap_action, _ns1__GetOnlineUserCount *ns1__GetOnlineUserCount, _ns1__GetOnlineUserCountResponse *ns1__GetOnlineUserCountResponse);

	/// Web service operation 'GetSupportedProductList' (returns error code or SOAP_OK)
	virtual	int GetSupportedProductList_(_ns1__GetSupportedProductList *ns1__GetSupportedProductList, _ns1__GetSupportedProductListResponse *ns1__GetSupportedProductListResponse) { return this->GetSupportedProductList_(NULL, NULL, ns1__GetSupportedProductList, ns1__GetSupportedProductListResponse); }
	virtual	int GetSupportedProductList_(const char *endpoint, const char *soap_action, _ns1__GetSupportedProductList *ns1__GetSupportedProductList, _ns1__GetSupportedProductListResponse *ns1__GetSupportedProductListResponse);

	/// Web service operation 'LookupServerByModule' (returns error code or SOAP_OK)
	virtual	int LookupServerByModule_(_ns1__LookupServerByModule *ns1__LookupServerByModule, _ns1__LookupServerByModuleResponse *ns1__LookupServerByModuleResponse) { return this->LookupServerByModule_(NULL, NULL, ns1__LookupServerByModule, ns1__LookupServerByModuleResponse); }
	virtual	int LookupServerByModule_(const char *endpoint, const char *soap_action, _ns1__LookupServerByModule *ns1__LookupServerByModule, _ns1__LookupServerByModuleResponse *ns1__LookupServerByModuleResponse);

	/// Web service operation 'RegisterPendingServers' (returns error code or SOAP_OK)
	virtual	int RegisterPendingServers_(_ns1__RegisterPendingServers *ns1__RegisterPendingServers, _ns1__RegisterPendingServersResponse *ns1__RegisterPendingServersResponse) { return this->RegisterPendingServers_(NULL, NULL, ns1__RegisterPendingServers, ns1__RegisterPendingServersResponse); }
	virtual	int RegisterPendingServers_(const char *endpoint, const char *soap_action, _ns1__RegisterPendingServers *ns1__RegisterPendingServers, _ns1__RegisterPendingServersResponse *ns1__RegisterPendingServersResponse);

	/// Web service operation 'LookupServerByGameType' (returns error code or SOAP_OK)
	virtual	int LookupServerByGameType_(_ns1__LookupServerByGameType *ns1__LookupServerByGameType, _ns1__LookupServerByGameTypeResponse *ns1__LookupServerByGameTypeResponse) { return this->LookupServerByGameType_(NULL, NULL, ns1__LookupServerByGameType, ns1__LookupServerByGameTypeResponse); }
	virtual	int LookupServerByGameType_(const char *endpoint, const char *soap_action, _ns1__LookupServerByGameType *ns1__LookupServerByGameType, _ns1__LookupServerByGameTypeResponse *ns1__LookupServerByGameTypeResponse);

	/// Web service operation 'GetClientExtensionUpdate' (returns error code or SOAP_OK)
	virtual	int GetClientExtensionUpdate_(_ns1__GetClientExtensionUpdate *ns1__GetClientExtensionUpdate, _ns1__GetClientExtensionUpdateResponse *ns1__GetClientExtensionUpdateResponse) { return this->GetClientExtensionUpdate_(NULL, NULL, ns1__GetClientExtensionUpdate, ns1__GetClientExtensionUpdateResponse); }
	virtual	int GetClientExtensionUpdate_(const char *endpoint, const char *soap_action, _ns1__GetClientExtensionUpdate *ns1__GetClientExtensionUpdate, _ns1__GetClientExtensionUpdateResponse *ns1__GetClientExtensionUpdateResponse);

	/// Web service operation 'LookupServerByGameTypeClientExtension' (returns error code or SOAP_OK)
	virtual	int LookupServerByGameTypeClientExtension_(_ns1__LookupServerByGameTypeClientExtension *ns1__LookupServerByGameTypeClientExtension, _ns1__LookupServerByGameTypeClientExtensionResponse *ns1__LookupServerByGameTypeClientExtensionResponse) { return this->LookupServerByGameTypeClientExtension_(NULL, NULL, ns1__LookupServerByGameTypeClientExtension, ns1__LookupServerByGameTypeClientExtensionResponse); }
	virtual	int LookupServerByGameTypeClientExtension_(const char *endpoint, const char *soap_action, _ns1__LookupServerByGameTypeClientExtension *ns1__LookupServerByGameTypeClientExtension, _ns1__LookupServerByGameTypeClientExtensionResponse *ns1__LookupServerByGameTypeClientExtensionResponse);

	/// Web service operation 'IncrementStatistic' (returns error code or SOAP_OK)
	virtual	int IncrementStatistic_(_ns1__IncrementStatistic *ns1__IncrementStatistic, _ns1__IncrementStatisticResponse *ns1__IncrementStatisticResponse) { return this->IncrementStatistic_(NULL, NULL, ns1__IncrementStatistic, ns1__IncrementStatisticResponse); }
	virtual	int IncrementStatistic_(const char *endpoint, const char *soap_action, _ns1__IncrementStatistic *ns1__IncrementStatistic, _ns1__IncrementStatisticResponse *ns1__IncrementStatisticResponse);
};
#endif
